"""End-to-end tests for the Granian ASGI path (TASK-472.6).

Boots oompah under Granian (subprocess, ASGI interface, workers=1) with a
minimal stub orchestrator wired in, then exercises four complete scenarios:

    1. HTTP root/state contract — GET / and /api/v1/state shape, status codes,
       content-types, JSON fields (running, api_metrics) asserted in one pass.
    2. WebSocket connection and initial push — handshake accepted; exactly two
       messages (``state`` and ``issues``) with correct structure.
    3. Broadcast fan-out — Client A sends ``{action: refresh}``; Client B
       receives the resulting ``broadcast_issues()`` message; requester also
       gets a state reply.
    4. Restart — server stops (SIGINT), a fresh process starts on the same
       port; HTTP contract is preserved and the WS initial push works again.

Skips cleanly if granian is not installed.

Design notes:
  • Each scenario uses the _granian_server() context manager which owns the
    full process lifecycle: start → identity capture → wait-ready → yield →
    identity-checked termination → pipe-drain. Cleanup runs even on assertion
    failure or KeyboardInterrupt, leaving no orphaned subprocesses.
  • The subprocess runs a one-shot Python script that calls
    ``oompah.server.set_orchestrator(stub)`` *before* ``Granian.serve()``.
    Because Granian 2.x with ``workers=1`` and the ASGI interface keeps the
    Python app in the same OS process, the module-level ``_orchestrator``
    reference is visible to the ASGI request handlers.
  • WebSocket tests use ``websockets.sync.client.connect`` (synchronous) to
    avoid nesting event loops inside the synchronous pytest runner.
  • Each scenario allocates a fresh ephemeral port so parallel test runs
    do not collide.
"""

from __future__ import annotations

import contextlib
import json
import os
import socket
import sys
import tempfile
import threading
import time
from pathlib import Path
from typing import Generator

import httpx
import pytest

from tests.process_lifecycle import OwnedProcess, start_owned_process, stop_owned_process

granian = pytest.importorskip("granian", reason="granian not installed")

# websockets.sync.client is available in websockets >= 12.0 (bundled via
# uvicorn[standard]).  Skip the WS-specific tests if it's absent.
try:
    from websockets.sync.client import connect as _ws_connect

    _WEBSOCKETS_SYNC_AVAILABLE = True
except ImportError:
    _WEBSOCKETS_SYNC_AVAILABLE = False

_ws_only = pytest.mark.skipif(
    not _WEBSOCKETS_SYNC_AVAILABLE,
    reason="websockets.sync.client not available",
)
_WS_RECV_TIMEOUT = 6.0


# ---------------------------------------------------------------------------
# Subprocess entry-point script template
# ---------------------------------------------------------------------------

_GRANIAN_E2E_SCRIPT = """\
# Granian e2e subprocess entry point (auto-generated by test_granian_e2e.py)
import os

import oompah.server as _srv

# ---------------------------------------------------------------------------
# Minimal stub orchestrator — satisfies set_orchestrator() without touching
# any real filesystem or tracker backend.
# ---------------------------------------------------------------------------

class _StubAgentProfileStore:
    def set_reload_callback(self, cb):
        pass


class _StubProjectStore:
    def list_all(self):
        return []

    def get(self, project_id):
        return None


class _StubTracker:
    def fetch_all_issues(self):
        return []


class _StubState:
    running = []


class _StubOrchestrator:
    def __init__(self):
        self._observers = []
        self._state_only_observers = []
        self._activity_observers = []
        self.tracker = _StubTracker()
        self.project_store = _StubProjectStore()
        self.agent_profile_store = _StubAgentProfileStore()
        self.role_store = object()
        self.provider_store = object()
        self.state = _StubState()
        self._unmerged_review_branches = set()

    def get_snapshot(self):
        return {{
            "running": [],
            "queued": [],
            "paused": False,
            "pid": os.getpid(),
        }}

    def replace_agent_profiles(self, profiles, source=""):
        pass

    def register_error_watcher(self, watcher, project_id=None):
        pass

    def _tracker_for_project(self, project_id):
        return self.tracker


_srv.set_orchestrator(_StubOrchestrator())

# ---------------------------------------------------------------------------
# Start Granian
# ---------------------------------------------------------------------------
from granian import Granian
from granian.constants import Interfaces

Granian(
    "oompah.server:app",
    address="127.0.0.1",
    port={port},
    interface=Interfaces.ASGI,
    workers=1,
    log_enabled=False,
).serve()
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _free_port() -> int:
    """Return an unused local TCP port."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        return sock.getsockname()[1]


def _start_granian_proc(port: int, workspace) -> OwnedProcess:
    """Launch the Granian e2e subprocess on *port* and return the Popen handle."""
    script = _GRANIAN_E2E_SCRIPT.format(port=port)
    env = os.environ.copy()
    repo_root = str(Path(__file__).resolve().parents[1])
    env["PYTHONPATH"] = repo_root + os.pathsep + env.get("PYTHONPATH", "")
    return start_owned_process(
        [sys.executable, "-c", script], workspace=workspace, env=env
    )


def _wait_ready(port: int, proc: OwnedProcess, timeout: float = 12.0) -> bool:
    """Poll until HTTP / returns 200 or the process exits early."""
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if proc.process.poll() is not None:
            return False
        try:
            r = httpx.get(f"http://127.0.0.1:{port}/", timeout=1.0)
            if r.status_code == 200:
                return True
        except Exception:
            pass
        time.sleep(0.1)
    return False


def _stop_proc(proc: OwnedProcess) -> None:
    """Bounded identity-checked shutdown, then drain pipes."""
    survivors = stop_owned_process(proc, timeout_s=8)
    try:
        proc.process.communicate(timeout=2)
    except Exception:
        pass
    assert proc.process.poll() is not None, (
        f"Granian process {proc.process.pid} was not reaped during shutdown"
    )
    assert not survivors, (
        f"Granian process tree still has survivors after shutdown: {sorted(survivors)}"
    )


def _wait_port_released(port: int, timeout: float = 5.0) -> bool:
    """Wait until no prior server owns *port* instead of sleeping blindly."""
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as probe:
            probe.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            try:
                probe.bind(("127.0.0.1", port))
            except OSError:
                time.sleep(0.05)
                continue
            return True
    return False


@contextlib.contextmanager
def _granian_server(port: int | None = None) -> Generator[str, None, None]:
    """Context manager: start a Granian E2E server, yield its base URL, then clean up.

    Process ownership is centralised here. Cleanup always executes bounded,
    identity-checked termination and drains stdout/stderr pipes, even when the
    body raises an assertion error or KeyboardInterrupt. This prevents
    orphaned Granian subprocesses regardless of test outcome.

    Args:
        port: TCP port to bind. Allocates an ephemeral port when *None*.

    Yields:
        ``http://127.0.0.1:<port>`` — base URL of the running server.
    """
    if port is None:
        port = _free_port()

    with tempfile.TemporaryDirectory(prefix="oompah-granian-") as raw_workspace:
        workspace = Path(raw_workspace)
        proc = _start_granian_proc(port, workspace)
        try:
            if not _wait_ready(port, proc):
                # Drain pipes before pytest.fail so they are not left open
                stdout, stderr = b"", b""
                try:
                    stdout, stderr = proc.process.communicate(timeout=3)
                except Exception:
                    pass
                pytest.fail(
                    f"Granian e2e server did not become ready on port {port}.\n"
                    f"stdout: {stdout.decode()[:400]}\n"
                    f"stderr: {stderr.decode()[:400]}"
                )

            yield f"http://127.0.0.1:{port}"
        finally:
            _stop_proc(proc)


def _ws_recv_json(ws, timeout: float = _WS_RECV_TIMEOUT) -> dict:
    """Receive one bounded WebSocket JSON message."""
    return json.loads(ws.recv(timeout=timeout))


def _drain_initial_ws_push(ws) -> list[dict]:
    """Drain the server's initial state + issues push (exactly two messages)."""
    return [_ws_recv_json(ws), _ws_recv_json(ws)]


# ---------------------------------------------------------------------------
# Scenario 1: HTTP root/state contract
# ---------------------------------------------------------------------------


def test_http_root_and_state_contract() -> None:
    """HTTP root and /api/v1/state contract — status codes, content-types, JSON fields.

    Combines assertions from the former TestGranianHTTPRoutes class (7 tests)
    into one scenario that starts a single Granian server:

    • GET / → 200, text/html, non-trivially long body
    • /api/v1/state → 200, application/json, contains ``running`` (empty list
      from stub orchestrator) and ``api_metrics``
    """
    with _granian_server() as base_url:
        # --- GET / ---
        r_root = httpx.get(base_url + "/")
        assert r_root.status_code == 200, (
            f"Expected 200 from GET /; got {r_root.status_code}"
        )
        ct_root = r_root.headers.get("content-type", "")
        assert "text/html" in ct_root, (
            f"Expected text/html content-type for GET /; got {ct_root!r}"
        )
        assert len(r_root.text) > 100, "Dashboard HTML body is unexpectedly short"

        # --- /api/v1/state ---
        r_state = httpx.get(base_url + "/api/v1/state")
        assert r_state.status_code == 200, (
            f"Expected 200 from /api/v1/state with stub orchestrator; got {r_state.status_code}. "
            "A 503 would mean the orchestrator was not wired into the worker process."
        )
        ct_state = r_state.headers.get("content-type", "")
        assert "application/json" in ct_state, (
            f"/api/v1/state Content-Type is {ct_state!r}, expected JSON"
        )
        body = r_state.json()
        assert "running" in body, (
            f"/api/v1/state response is missing 'running' field. Got keys: {list(body.keys())}"
        )
        assert body["running"] == [], (
            f"Expected running=[] from stub orchestrator; got {body['running']!r}"
        )
        assert "api_metrics" in body, (
            f"/api/v1/state response is missing 'api_metrics'. Got keys: {list(body.keys())}"
        )


# ---------------------------------------------------------------------------
# Scenario 2: WebSocket connection and initial push
# ---------------------------------------------------------------------------


@pytest.mark.skipif(
    not _WEBSOCKETS_SYNC_AVAILABLE, reason="websockets.sync.client unavailable"
)
@pytest.mark.timeout(20)
def test_ws_connection_and_initial_push() -> None:
    """WebSocket handshake accepted; initial push delivers state + issues messages.

    Combines assertions from the former TestGranianWebSocketInitialPush class
    (6 fixture-based tests) into one scenario with a single Granian server:

    • Handshake succeeds without error
    • Exactly two messages are sent immediately after connect
    • Both messages are well-formed JSON objects with ``type`` and ``data`` keys
    • Message types include both ``state`` and ``issues``
    • The ``state`` message's data contains a ``running`` key
    """
    with _granian_server() as base_url:
        uri = base_url.replace("http://", "ws://") + "/ws"

        with _ws_connect(uri) as ws:
            msgs = _drain_initial_ws_push(ws)
            # Drain complete before closing so the single-worker Granian process
            # is not stuck in a partial handshake state.

    # Two messages
    assert len(msgs) == 2, (
        f"Expected 2 initial messages; got {len(msgs)}: {msgs}"
    )

    # Both are well-formed JSON objects
    for msg in msgs:
        assert isinstance(msg, dict), f"Message is not a dict: {msg!r}"
        assert "type" in msg, f"Message missing 'type': {msg!r}"
        assert "data" in msg, f"Message missing 'data': {msg!r}"

    # Both required types are present
    types = {msg["type"] for msg in msgs}
    assert "state" in types, (
        f"Initial WS push did not include a 'state' message; got types: {types}"
    )
    assert "issues" in types, (
        f"Initial WS push did not include an 'issues' message; got types: {types}"
    )

    # State message has the running field
    state_msg = next(m for m in msgs if m["type"] == "state")
    assert "running" in state_msg.get("data", {}), (
        f"state message data is missing 'running'. data keys: {list(state_msg.get('data', {}).keys())}"
    )


# ---------------------------------------------------------------------------
# Scenario 3: Broadcast fan-out (two concurrent clients)
# ---------------------------------------------------------------------------


@pytest.mark.skipif(
    not _WEBSOCKETS_SYNC_AVAILABLE, reason="websockets.sync.client unavailable"
)
def test_ws_broadcast_fan_out() -> None:
    """orchestrator → _broadcast → WS client fan-out under Granian.

    Combines assertions from the former TestGranianBroadcast class (3 tests)
    into one scenario with a single Granian server:

    • Client A's ``{action: refresh}`` triggers broadcast_issues(), which
      fans out to all connected clients.
    • Client B (connected concurrently) receives the broadcast as a valid JSON
      object of type ``issues``.
    • Client A (the requester) also receives a ``state`` or ``issues`` reply.
    """
    with _granian_server() as base_url:
        uri = base_url.replace("http://", "ws://") + "/ws"

        client_b_received: list[dict] = []
        client_b_error: list[Exception] = []

        def _run_client_b() -> None:
            """Background thread: connect, drain initial push, collect broadcast."""
            try:
                with _ws_connect(uri) as ws_b:
                    _drain_initial_ws_push(ws_b)
                    # Wait up to 6 s for the broadcast triggered by client A
                    try:
                        client_b_received.append(_ws_recv_json(ws_b))
                    except Exception as exc:
                        client_b_error.append(exc)
            except Exception as exc:
                client_b_error.append(exc)

        with _ws_connect(uri) as ws_a:
            # Drain client A's initial push
            _drain_initial_ws_push(ws_a)

            # Start client B in background and give it time to connect and
            # drain its own initial push before client A fires the refresh.
            t = threading.Thread(target=_run_client_b, daemon=True)
            t.start()
            time.sleep(0.4)  # let B connect + drain

            # Trigger broadcast from client A
            ws_a.send(json.dumps({"action": "refresh"}))

            # Also collect what client A (the requester) receives
            requester_msgs: list[dict] = []
            for _ in range(3):
                try:
                    requester_msgs.append(_ws_recv_json(ws_a))
                except Exception:
                    break

            t.join(timeout=8)

    # --- Client B assertions ---
    assert not t.is_alive(), "Client B thread did not finish"
    assert not client_b_error, (
        f"Client B raised an exception: {client_b_error[0]!r}"
    )
    assert len(client_b_received) > 0, (
        "Client B did not receive any broadcast message after client A sent "
        "{action: refresh}. This suggests _broadcast did not fan-out under Granian."
    )
    broadcast_msg = client_b_received[0]
    assert isinstance(broadcast_msg, dict), (
        f"Broadcast message is not a dict: {broadcast_msg!r}"
    )
    assert "type" in broadcast_msg, f"Broadcast message missing 'type': {broadcast_msg!r}"
    assert "data" in broadcast_msg, f"Broadcast message missing 'data': {broadcast_msg!r}"
    assert broadcast_msg.get("type") == "issues", (
        f"Client B expected to receive 'issues' broadcast; got type={broadcast_msg.get('type')!r}"
    )

    # --- Requester (client A) assertions ---
    requester_types = {m.get("type") for m in requester_msgs}
    assert "state" in requester_types or "issues" in requester_types, (
        f"Expected state or issues message after refresh; got types: {requester_types}"
    )


# ---------------------------------------------------------------------------
# Scenario 4: Restart — stop and start on same port, verify HTTP + WS
# ---------------------------------------------------------------------------


@pytest.mark.timeout(30)
def test_restart_http_and_ws_contract() -> None:
    """Server restarts on the same port; HTTP contract and WS initial push preserved.

    Combines assertions from the former TestGranianRestart class (3 tests):

    • After stop + restart on the same port the server serves HTTP (200s).
    • GET / and /api/v1/state status codes and content-types match first boot.
    • /api/v1/state body still contains the ``running`` field.
    • WebSocket initial push (state + issues) works on the restarted server.
    """
    port = _free_port()

    # --- First server: record baseline HTTP contract ---
    with _granian_server(port=port) as base_url_1:
        r_root_1 = httpx.get(f"{base_url_1}/", timeout=2.0)
        r_state_1 = httpx.get(f"{base_url_1}/api/v1/state", timeout=2.0)
        assert r_root_1.status_code == 200, (
            f"First server: expected 200 from GET /; got {r_root_1.status_code}"
        )
        assert r_state_1.status_code == 200, (
            f"First server: expected 200 from /api/v1/state; got {r_state_1.status_code}"
        )
        first_root_ct = r_root_1.headers.get("content-type")
        first_state_ct = r_state_1.headers.get("content-type")
    # _granian_server exits here: SIGINT → drain; port is released

    assert _wait_port_released(port), (
        f"First Granian server did not release port {port} after owned shutdown"
    )

    # --- Second server: verify HTTP preserved and WS works ---
    with _granian_server(port=port) as base_url_2:
        # HTTP status codes preserved
        r_root_2 = httpx.get(f"{base_url_2}/", timeout=2.0)
        r_state_2 = httpx.get(f"{base_url_2}/api/v1/state", timeout=2.0)
        assert r_root_2.status_code == r_root_1.status_code, (
            f"GET / status changed after restart: "
            f"{r_root_1.status_code} → {r_root_2.status_code}"
        )
        assert r_state_2.status_code == r_state_1.status_code, (
            f"/api/v1/state status changed after restart: "
            f"{r_state_1.status_code} → {r_state_2.status_code}"
        )

        # Content-type headers preserved
        assert r_root_2.headers.get("content-type") == first_root_ct, (
            "GET / content-type changed after restart"
        )
        assert r_state_2.headers.get("content-type") == first_state_ct, (
            "/api/v1/state content-type changed after restart"
        )

        # JSON body still has the running field
        body = r_state_2.json()
        assert "running" in body, (
            f"Restarted server: /api/v1/state missing 'running' field. "
            f"Got: {list(body.keys())}"
        )

        # WebSocket initial push still works after restart
        if _WEBSOCKETS_SYNC_AVAILABLE:
            uri = f"ws://127.0.0.1:{port}/ws"
            with _ws_connect(uri) as ws:
                ws_types = {m["type"] for m in _drain_initial_ws_push(ws)}
            assert "state" in ws_types and "issues" in ws_types, (
                f"WS initial push after restart: expected state+issues; got {ws_types}"
            )
