"""Helpers for keeping managed-repo AGENTS.md task instructions current."""

from __future__ import annotations

import re
from pathlib import Path


GITHUB_ISSUES_AGENT_INSTRUCTIONS = """<!-- BEGIN OOMPAH GITHUB ISSUES INTEGRATION v:1 -->
## Issue Tracking with GitHub Issues

This project is managed by **oompah** using **GitHub Issues** as the
canonical task tracker. Do **not** create or edit Backlog.md task files, do
not use the `backlog` CLI for task tracking, and do not use `bd`, beads,
TodoWrite, markdown TODO lists, or another tracker for project work.

Use the `oompah task` CLI so oompah can apply the correct GitHub labels,
status mapping, parent/child links, dependencies, and comments.

### Quick Reference

```bash
oompah task view <owner/repo#number>
oompah task comment <owner/repo#number> --message "Progress update" --author oompah
oompah task create --project <project-id> --title "Follow-up title" --description "Details" --source <owner/repo#number>
oompah task child-create <owner/repo#number> --title "Child task title" --description "Details"
oompah task set-dependency <owner/repo#number> --depends-on <owner/repo#other-number>
oompah task add-label <owner/repo#number> needs:frontend
oompah task set-status <owner/repo#number> Open
oompah task set-status <owner/repo#number> Done --summary "Completed"
```

### Rules

- Always pass `--author oompah` when posting comments.
- Use `oompah task create --project <project-id>` for follow-up work so the
  issue is created in the configured project tracker.
- Use `oompah task child-create <parent>` for epic children; do not hand-write
  `parent:*` labels.
- Do not edit `oompah:status:*`, `type:*`, `priority:*`, `parent:*`, or
  `depends-on:*` labels directly unless you are fixing the tracker adapter.
- Epics use `type:epic`; their effective status is derived from child issue
  status by oompah.
- Existing `backlog/` files are legacy history. Do not add new files there for
  task tracking after GitHub Issues cutover.

## Session Completion

When ending a work session, complete all of these steps:

1. File follow-up issues with `oompah task create` for remaining work.
2. Run the relevant quality gates for the code you changed.
3. Update the current issue status or leave a clear handoff comment.
4. Push all committed work:
   ```bash
   git pull --rebase
   git push
   git status
   ```
5. Verify `git status` reports the branch is up to date with origin.

Work is not complete until the code is pushed and the GitHub issue is updated.
Never leave finished work only in a local commit.

<!-- END OOMPAH GITHUB ISSUES INTEGRATION -->
"""


_GITHUB_BLOCK_RE = re.compile(
    r"<!-- BEGIN OOMPAH GITHUB ISSUES INTEGRATION(?: [^>]*)? -->.*?"
    r"<!-- END OOMPAH GITHUB ISSUES INTEGRATION -->",
    re.DOTALL,
)
_BACKLOG_BLOCK_RE = re.compile(
    r"<!-- BEGIN BACKLOG INTEGRATION(?: [^>]*)? -->.*?"
    r"<!-- END BACKLOG INTEGRATION -->",
    re.DOTALL,
)
_TOP_BACKLOG_QUICK_REF_RE = re.compile(
    r"\n*This project uses \*\*Backlog\.md\*\* for issue tracking\..*?"
    r"## Quick Reference\s*\n\s*```bash\s*\n"
    r"backlog task list --plain.*?"
    r"backlog board --plain.*?"
    r"```\s*\n",
    re.DOTALL,
)


def render_github_issues_agent_instructions() -> str:
    """Return the canonical AGENTS.md GitHub Issues task-tracking block."""

    return GITHUB_ISSUES_AGENT_INSTRUCTIONS


def update_agents_text_for_github_issues(text: str) -> tuple[str, bool]:
    """Return AGENTS.md text with oompah GitHub Issues instructions installed.

    The updater handles the two common managed-repo shapes:

    * a marker-delimited Backlog integration block generated by oompah;
    * the older top-of-file Backlog quick reference used by oompah itself.

    Unknown custom text is left in place and the canonical GitHub block is
    appended when no managed block exists.
    """

    original = text
    updated = text

    if _TOP_BACKLOG_QUICK_REF_RE.search(updated):
        has_managed_block = bool(
            _GITHUB_BLOCK_RE.search(updated) or _BACKLOG_BLOCK_RE.search(updated)
        )
        replacement = "\n\n"
        if not has_managed_block:
            replacement = "\n\n" + GITHUB_ISSUES_AGENT_INSTRUCTIONS.strip() + "\n\n"
        updated = _TOP_BACKLOG_QUICK_REF_RE.sub(
            replacement,
            updated,
            count=1,
        )

    if _GITHUB_BLOCK_RE.search(updated):
        updated = _GITHUB_BLOCK_RE.sub(
            GITHUB_ISSUES_AGENT_INSTRUCTIONS.strip(),
            updated,
            count=1,
        )
    elif _BACKLOG_BLOCK_RE.search(updated):
        updated = _BACKLOG_BLOCK_RE.sub(
            GITHUB_ISSUES_AGENT_INSTRUCTIONS.strip(),
            updated,
            count=1,
        )
    else:
        suffix = "" if updated.endswith("\n") else "\n"
        updated = (
            updated
            + suffix
            + "\n"
            + GITHUB_ISSUES_AGENT_INSTRUCTIONS.strip()
            + "\n"
        )

    # Keep a single trailing newline and avoid churn when no semantic change
    # was needed.
    updated = updated.rstrip() + "\n"
    return updated, updated != original


def ensure_github_issues_agent_instructions(repo_path: str | Path) -> bool:
    """Install GitHub Issues task instructions into ``repo_path/AGENTS.md``.

    Returns ``True`` when the file changed, ``False`` when it already matched.
    Missing repositories or missing AGENTS.md files raise ``OSError`` so callers
    can decide whether to make cutover strict or best-effort.
    """

    agents_path = Path(repo_path) / "AGENTS.md"
    text = agents_path.read_text(encoding="utf-8")
    updated, changed = update_agents_text_for_github_issues(text)
    if changed:
        agents_path.write_text(updated, encoding="utf-8")
    return changed
